### PR TITLE
Change InfoResult::Attributes Returned Value to Array of Arrays

### LINKED ISSUE #291: Index.Attribute throws error for sortable fields
**NRedisStack Version**: 0.12.0
**Redis Stack Version**: 
image

**Description**: 
For sorted attributes , index.Attributes throws  _request.System.IndexOutOfRangeException: Index was outside the bounds of the array._
image

This is how i add text field: 
                            schema.AddTextField(item.Key, sortable: true);

This is how index is created 

var ftCreateParams = new FTCreateParams().On(IndexDataType.HASH)
                                        .Temporary(expiryTime)
                                        .Prefix(payloadPrefix);

note that , almost all of the fields are marked as sortable

**This issue does not happen when i mark the fields false for sortable.**

Please help !

### PR DESCRIPTION
**Pull request by shacharPash**
Fixes #291

### CODE REVIEW

**Review by dvora-h — APPROVED** [review]

File: src/NRedisStack/Search/DataTypes/InfoResult.cs [hunk 1]
```diff
@@ -91,26 +91,29 @@ private double GetDouble(string key)
...
-            }
-
-            result[i] = dict;
-        }
-
-        return result;
+        return value.ToArrayArray();
     }
+
+    // private Dictionary<string, RedisResult>[]? GetRedisResultDictionaryArray(string key)
```
Comment (uglide) [inline src/NRedisStack/Search/DataTypes/InfoResult.cs:102]: Why not remove it instead?

File: tests/NRedisStack.Tests/Search/SearchTests.cs [hunk 2]
```diff
@@ -702,7 +702,7 @@ public void AlterAdd()
         IDatabase db = redisFixture.Redis.GetDatabase();
         db.Execute("FLUSHALL");
         var ft = db.FT();
-        Schema sc = new Schema().AddTextField("title", 1.0);
+        Schema sc = new Schema().AddTextField("title", 1.0, sortable: true);
```
Comment (uglide) [inline tests/NRedisStack.Tests/Search/SearchTests.cs:705]: I think we need to test both cases with sortable and not sortable text fields to ensure it's still usable for not sortable.

**Review by uglide — CHANGES_REQUESTED** [review]

**Review by uglide — APPROVED** [review]
LGTM
