### PR TITLE
Change TimeStamp from DateTime to Millisecond Instead of Ticks

### LINKED ISSUE #126: TimeStamp from DateTime not working
When creating the TimeStamp from DateTime the code takes total ticks. As stated in definition there are 10,000 ticks in a millisecond (see [TicksPerMillisecond](https://learn.microsoft.com/en-us/dotnet/api/system.timespan.tickspermillisecond?view=net-8.0)) and 10 million ticks in a second. To redis it supplied just calling ToString() method but redis expects the timestamp in miliseconds.

### PR DESCRIPTION
**Pull request by shacharPash**
Closes #126

### CODE REVIEW

File: src/NRedisStack/TimeSeries/DataTypes/TimeStamp.cs [hunk 1]
```diff
@@ -23,7 +23,7 @@ public class TimeStamp
         /// Build a TimeStamp from DateTime.
         /// </summary>
         /// <param name="dateTime">DateTime value</param>
-        public TimeStamp(DateTime dateTime) => Value = dateTime.Ticks;
+        public TimeStamp(DateTime dateTime) => Value = (long) dateTime.Millisecond; // TODO: Check this
```
Comment (slorello89) [inline src/NRedisStack/TimeSeries/DataTypes/TimeStamp.cs:26]: Both the new and old here will produce timestamps from January 1st 1970, `Ticks` and `Millisecond` are both components of the timestamp, they do not represent the unix millisecond timestamp of `DateTime.`

You will need to use the DateTimeOffset struct to produce what is needed here:

```suggestion
        public TimeStamp(DateTime dateTime) => Value = new DateTimeOffset(dateTime).ToUnixTimeMilliseconds();
```

**Review by slorello89 — APPROVED** [review]

**Review by slorello89 — CHANGES_REQUESTED** [review]
See comment above

**Review by slorello89 — APPROVED** [review]
LGTM 👍
